import type { Board } from './interfaces'
import { Horizontal, Vertical, Side, Piece } from './enums'

export const getNewBoard = (): Board => {
  return {
    squares: [
      [
        {
          id: 0,
          x: Horizontal.eight,
          y: Vertical.a,
          item: { side: Side.dark, piece: Piece.rook },
        },
        {
          id: 1,
          x: Horizontal.seven,
          y: Vertical.a,
          item: { side: Side.dark, piece: Piece.pawn },
        },
        { id: 2, x: Horizontal.six, y: Vertical.a },
        { id: 3, x: Horizontal.five, y: Vertical.a },
        { id: 4, x: Horizontal.four, y: Vertical.a },
        { id: 5, x: Horizontal.three, y: Vertical.a },
        {
          id: 6,
          x: Horizontal.two,
          y: Vertical.a,
          item: { side: Side.light, piece: Piece.pawn },
        },
        {
          id: 7,
          x: Horizontal.one,
          y: Vertical.a,
          item: { side: Side.light, piece: Piece.rook },
        },
      ],
      [
        {
          id: 8,
          x: Horizontal.eight,
          y: Vertical.b,
          item: { side: Side.dark, piece: Piece.knight },
        },
        {
          id: 9,
          x: Horizontal.seven,
          y: Vertical.b,
          item: { side: Side.dark, piece: Piece.pawn },
        },
        { id: 10, x: Horizontal.six, y: Vertical.b },
        { id: 11, x: Horizontal.five, y: Vertical.b },
        { id: 12, x: Horizontal.four, y: Vertical.b },
        { id: 13, x: Horizontal.three, y: Vertical.b },
        {
          id: 14,
          x: Horizontal.two,
          y: Vertical.b,
          item: { side: Side.light, piece: Piece.pawn },
        },
        {
          id: 15,
          x: Horizontal.one,
          y: Vertical.b,
          item: { side: Side.light, piece: Piece.knight },
        },
      ],
      [
        {
          id: 16,
          x: Horizontal.eight,
          y: Vertical.c,
          item: { side: Side.dark, piece: Piece.bishop },
        },
        {
          id: 17,
          x: Horizontal.seven,
          y: Vertical.c,
          item: { side: Side.dark, piece: Piece.pawn },
        },
        { id: 18, x: Horizontal.six, y: Vertical.c },
        { id: 19, x: Horizontal.five, y: Vertical.c },
        { id: 20, x: Horizontal.four, y: Vertical.c },
        { id: 21, x: Horizontal.three, y: Vertical.c },
        {
          id: 22,
          x: Horizontal.two,
          y: Vertical.c,
          item: { side: Side.light, piece: Piece.pawn },
        },
        {
          id: 23,
          x: Horizontal.one,
          y: Vertical.c,
          item: { side: Side.light, piece: Piece.bishop },
        },
      ],
      [
        {
          id: 24,
          x: Horizontal.eight,
          y: Vertical.d,
          item: { side: Side.dark, piece: Piece.queen },
        },
        {
          id: 25,
          x: Horizontal.seven,
          y: Vertical.d,
          item: { side: Side.dark, piece: Piece.pawn },
        },
        { id: 26, x: Horizontal.six, y: Vertical.d },
        { id: 27, x: Horizontal.five, y: Vertical.d },
        { id: 28, x: Horizontal.four, y: Vertical.d },
        { id: 29, x: Horizontal.three, y: Vertical.d },
        {
          id: 30,
          x: Horizontal.two,
          y: Vertical.d,
          item: { side: Side.light, piece: Piece.pawn },
        },
        {
          id: 31,
          x: Horizontal.one,
          y: Vertical.d,
          item: { side: Side.light, piece: Piece.queen },
        },
      ],
      [
        {
          id: 32,
          x: Horizontal.eight,
          y: Vertical.e,
          item: { side: Side.dark, piece: Piece.king },
        },
        {
          id: 33,
          x: Horizontal.seven,
          y: Vertical.e,
          item: { side: Side.dark, piece: Piece.pawn },
        },
        { id: 34, x: Horizontal.six, y: Vertical.e },
        { id: 35, x: Horizontal.five, y: Vertical.e },
        { id: 36, x: Horizontal.four, y: Vertical.e },
        { id: 37, x: Horizontal.three, y: Vertical.e },
        {
          id: 38,
          x: Horizontal.two,
          y: Vertical.e,
          item: { side: Side.light, piece: Piece.pawn },
        },
        {
          id: 39,
          x: Horizontal.one,
          y: Vertical.e,
          item: { side: Side.light, piece: Piece.king },
        },
      ],
      [
        {
          id: 40,
          x: Horizontal.eight,
          y: Vertical.f,
          item: { side: Side.dark, piece: Piece.bishop },
        },
        {
          id: 41,
          x: Horizontal.seven,
          y: Vertical.f,
          item: { side: Side.dark, piece: Piece.pawn },
        },
        { id: 42, x: Horizontal.six, y: Vertical.f },
        { id: 43, x: Horizontal.five, y: Vertical.f },
        { id: 44, x: Horizontal.four, y: Vertical.f },
        { id: 45, x: Horizontal.three, y: Vertical.f },
        {
          id: 46,
          x: Horizontal.two,
          y: Vertical.f,
          item: { side: Side.light, piece: Piece.pawn },
        },
        {
          id: 47,
          x: Horizontal.one,
          y: Vertical.f,
          item: { side: Side.light, piece: Piece.bishop },
        },
      ],
      [
        {
          id: 48,
          x: Horizontal.eight,
          y: Vertical.g,
          item: { side: Side.dark, piece: Piece.knight },
        },
        {
          id: 49,
          x: Horizontal.seven,
          y: Vertical.g,
          item: { side: Side.dark, piece: Piece.pawn },
        },
        { id: 50, x: Horizontal.six, y: Vertical.g },
        { id: 51, x: Horizontal.five, y: Vertical.g },
        { id: 52, x: Horizontal.four, y: Vertical.g },
        { id: 53, x: Horizontal.three, y: Vertical.g },
        {
          id: 54,
          x: Horizontal.two,
          y: Vertical.g,
          item: { side: Side.light, piece: Piece.pawn },
        },
        {
          id: 55,
          x: Horizontal.one,
          y: Vertical.g,
          item: { side: Side.light, piece: Piece.knight },
        },
      ],
      [
        {
          id: 56,
          x: Horizontal.eight,
          y: Vertical.h,
          item: { side: Side.dark, piece: Piece.rook },
        },
        {
          id: 57,
          x: Horizontal.seven,
          y: Vertical.h,
          item: { side: Side.dark, piece: Piece.pawn },
        },
        { id: 58, x: Horizontal.six, y: Vertical.h },
        { id: 59, x: Horizontal.five, y: Vertical.h },
        { id: 60, x: Horizontal.four, y: Vertical.h },
        { id: 61, x: Horizontal.three, y: Vertical.h },
        {
          id: 62,
          x: Horizontal.two,
          y: Vertical.h,
          item: { side: Side.light, piece: Piece.pawn },
        },
        {
          id: 63,
          x: Horizontal.one,
          y: Vertical.h,
          item: { side: Side.light, piece: Piece.rook },
        },
      ],
    ],
  }
}
