import type { Board } from './interfaces'
import { Horizontal, Vertical } from './enums'

export const getEmptyBoard = (): Board => {
  return {
    squares: [
      [
        { id: 0, x: Horizontal.eight, y: Vertical.a },
        { id: 1, x: Horizontal.seven, y: Vertical.a },
        { id: 2, x: Horizontal.six, y: Vertical.a },
        { id: 3, x: Horizontal.five, y: Vertical.a },
        { id: 4, x: Horizontal.four, y: Vertical.a },
        { id: 5, x: Horizontal.three, y: Vertical.a },
        { id: 6, x: Horizontal.two, y: Vertical.a },
        { id: 7, x: Horizontal.one, y: Vertical.a },
      ],
      [
        { id: 8, x: Horizontal.eight, y: Vertical.b },
        { id: 9, x: Horizontal.seven, y: Vertical.b },
        { id: 10, x: Horizontal.six, y: Vertical.b },
        { id: 11, x: Horizontal.five, y: Vertical.b },
        { id: 12, x: Horizontal.four, y: Vertical.b },
        { id: 13, x: Horizontal.three, y: Vertical.b },
        { id: 14, x: Horizontal.two, y: Vertical.b },
        { id: 15, x: Horizontal.one, y: Vertical.b },
      ],
      [
        { id: 16, x: Horizontal.eight, y: Vertical.c },
        { id: 17, x: Horizontal.seven, y: Vertical.c },
        { id: 18, x: Horizontal.six, y: Vertical.c },
        { id: 19, x: Horizontal.five, y: Vertical.c },
        { id: 20, x: Horizontal.four, y: Vertical.c },
        { id: 21, x: Horizontal.three, y: Vertical.c },
        { id: 22, x: Horizontal.two, y: Vertical.c },
        { id: 23, x: Horizontal.one, y: Vertical.c },
      ],
      [
        { id: 24, x: Horizontal.eight, y: Vertical.d },
        { id: 25, x: Horizontal.seven, y: Vertical.d },
        { id: 26, x: Horizontal.six, y: Vertical.d },
        { id: 27, x: Horizontal.five, y: Vertical.d },
        { id: 28, x: Horizontal.four, y: Vertical.d },
        { id: 29, x: Horizontal.three, y: Vertical.d },
        { id: 30, x: Horizontal.two, y: Vertical.d },
        { id: 31, x: Horizontal.one, y: Vertical.d },
      ],
      [
        { id: 32, x: Horizontal.eight, y: Vertical.e },
        { id: 33, x: Horizontal.seven, y: Vertical.e },
        { id: 34, x: Horizontal.six, y: Vertical.e },
        { id: 35, x: Horizontal.five, y: Vertical.e },
        { id: 36, x: Horizontal.four, y: Vertical.e },
        { id: 37, x: Horizontal.three, y: Vertical.e },
        { id: 38, x: Horizontal.two, y: Vertical.e },
        { id: 39, x: Horizontal.one, y: Vertical.e },
      ],
      [
        { id: 40, x: Horizontal.eight, y: Vertical.f },
        { id: 41, x: Horizontal.seven, y: Vertical.f },
        { id: 42, x: Horizontal.six, y: Vertical.f },
        { id: 43, x: Horizontal.five, y: Vertical.f },
        { id: 44, x: Horizontal.four, y: Vertical.f },
        { id: 45, x: Horizontal.three, y: Vertical.f },
        { id: 46, x: Horizontal.two, y: Vertical.f },
        { id: 47, x: Horizontal.one, y: Vertical.f },
      ],
      [
        { id: 48, x: Horizontal.eight, y: Vertical.g },
        { id: 49, x: Horizontal.seven, y: Vertical.g },
        { id: 50, x: Horizontal.six, y: Vertical.g },
        { id: 51, x: Horizontal.five, y: Vertical.g },
        { id: 52, x: Horizontal.four, y: Vertical.g },
        { id: 53, x: Horizontal.three, y: Vertical.g },
        { id: 54, x: Horizontal.two, y: Vertical.g },
        { id: 55, x: Horizontal.one, y: Vertical.g },
      ],
      [
        { id: 56, x: Horizontal.eight, y: Vertical.h },
        { id: 57, x: Horizontal.seven, y: Vertical.h },
        { id: 58, x: Horizontal.six, y: Vertical.h },
        { id: 59, x: Horizontal.five, y: Vertical.h },
        { id: 60, x: Horizontal.four, y: Vertical.h },
        { id: 61, x: Horizontal.three, y: Vertical.h },
        { id: 62, x: Horizontal.two, y: Vertical.h },
        { id: 63, x: Horizontal.one, y: Vertical.h },
      ],
    ],
  }
}
